on:
  push:
    branches: [master]
  pull_request:

name: CI

jobs:
  test:
    name: Build website
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build --no-cache .
