on:
  push:
    branches: [master]
  schedule:
    - cron: '30 3 * * 2'

name: Publish

jobs:
  publish:
    name: Publish Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: |
          docker build \
            --no-cache \
            -t spaceapi/website:latest \
            -t spaceapi/website:v3 \
            -t spaceapi/website:master \
            .
      - name: Push Docker image
        run: |
          docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}" && \
          docker push -a spaceapi/website
